### ISSUE TITLE
slow to open log file

### ISSUE THREAD

**Issue by laoshaw** [MTDL9/vim-log-highlighting#8]
with a 1MB log file(7000 lines) it took 1 minute to open, is this normal?

**Comment by MTDL9** [comment]
Hi, sorry for the delayed response.

I regularly open log files larger than 1 GB without problem (takes less than a second to open VIM), so it is not normal that it takes 1 minute to open a 1MB file.


A possible cause for the slowness might be some configuration that forces the rendering of the syntax of entire file.

Do you have any directive like this in your .vimrc?
```viml
autocmd BufEnter * :syntax sync fromstart
```
Or a large value of minlines, like this?
```viml
syntax sync minlines=10000
```


Another possible cause might be an issue with some of the Regex rules, triggered by the structure of your file. Can you share a snippet (or the entirety, if you do not have sensitive data inside) of your log file?

**Comment by MTDL9** [comment]
There was an issue with the logXmlEntity rule that caused long opening times if the file contained very long words (see #10), this issue might be resolved by the latest commit. Assuming as resolved since no feedback has been received, feel free to comment if you still have the problem and I'll reopen this
